name: build and publish a release

on:
  release:
    types: [published]

jobs:
  maven-central:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_PORTAL_TOKEN_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_PORTAL_TOKEN_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PGP_SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.PGP_SIGNING_PASSWORD }}
    steps:
      - name: Setup
        uses: kosi-libs/kodein-internal-github-actions/setup@main
        with:
          konan: false
      - name: Build
        run: ./gradlew --stacktrace --scan Compose-Ur-Pres:build
      - name: Publish
        run: ./gradlew --stacktrace --scan -PRELEASE_SIGNING_ENABLED=true Compose-Ur-Pres:publishAndReleaseToMavenCentral
        shell: bash

  gradle-portal:
    runs-on: ubuntu-latest
    needs: [maven-central]
    steps:
      - name: Setup
        uses: kosi-libs/kodein-internal-github-actions/setup@main
        with:
          konan: false
      - name: Publish
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew --stacktrace --scan -PRELEASE_SIGNING_ENABLED=true Compose-Ur-Pres:cup-gradle-plugin:publishPlugins
